# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashanddineapp', '0005_orderdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'details'},
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashanddineapp.Driver'),
        ),
    ]
