# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashanddineapp', '0006_auto_20170301_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
